# Generated by Django 3.2 on 2021-04-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Omzi's DevLog", max_length=255),
        ),
    ]
