# Generated by Django 3.2 on 2021-04-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
