# Generated by Django 3.2 on 2021-04-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_post_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_published',
        ),
    ]
