# Generated by Django 3.2 on 2021-04-30 00:06

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.photo_path),
        ),
    ]
